### ISSUE TITLE
Datos históricos: ¿los valores representados por el inicio o por el final?

### ISSUE THREAD

**Issue by ldotlopez** [ldotlopez/ideenergy#1]
Suponemos un consumo entre las 03:00 y 04:00 de 0,1 kwh.

¿Qué valor de tiempo debería acompañar a ese dato? `datatime.datetime(2022, 1, 1 , 3, 0, 0)` o `datatime.datetime(2022, 1, 1, 4, 0, 0)`

Actualmente se usa el valor del inicio de periodo pero tal vez no sea el correcto.

**Comment by kikediazfernandez** [comment]
Yo creo que es mejor tal cual, para que si filtras en el día efectivamente tengas el consumo de todo el día. Si lo pones al final del periodo, el consumo de 23 a 24 lo vas a mostrar en las 00:00 del día siguiente

**Comment by ldotlopez** [comment]
Desde hace tiempo vengo usando el valor de final de periodo para representar el consumo, es lo que mejor encaja con home-assistant y con mi experiencia.

El caso que comentas actualmente se representa correctamente.

De todos modos si encuentras algún caso donde los datos puedan resultar confusos abre una issue.

Saludos

**Comment by ldotlopez** [comment]
Disculpa, creía que estaba comentando sobre la integraciín con HomeAsistant.

Actualmente los datos se presentan tal cual vienen del API de i-de:
https://github.com/ldotlopez/ideenergy/blob/main/ideenergy/parsers.py#L26
